# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2026 callmetango for XLibre

name: Release packages
description: Release the built packages

inputs:
  repository:
    description: |-
      Location of the GitHub repository containing the package descriptions
      in the form of [HOST/]OWNER/REPO.
  branch:
    description: The branch to build
    required: true
  repo-db-prefix:
    description: Prefix of the package repository database

  # App-based authentication
  app-client-id:
    description: GitHub App Client ID
  app-private-key: # secret
    description: the private key of the app used for token generation

runs:
  using: composite
  steps:
    - name: Authenticate via app
      id: app-token
      if: ${{ inputs.app-client-id }}
      uses: actions/create-github-app-token@v3
      with:
        client-id: ${{ inputs.app-client-id }}
        private-key: ${{ inputs.app-private-key }}
        owner: ${{ github.repository_owner }}

    - name: Checkout workflow # so we can run our scripts
      uses: actions/checkout@v6

    - name: Setup env and download packages
      shell: sh
      env:
        APP_TOKEN: ${{ steps.app-token.outputs.token }}
        INPUT_BRANCH: ${{ inputs.branch }}
        INPUT_REPO_DB_PREFIX: ${{ inputs.repo-db-prefix }}
        SCRIPTS_DIR: ${{ github.workspace }}/.github/scripts
      run: |
        . "$SCRIPTS_DIR"/gh-helpers.sh
        . "$SCRIPTS_DIR"/setup-build-env.sh

        gh_env_set REPO_NAME "${INPUT_REPO_DB_PREFIX}-${RELEASE_BRANCH}"

        gh release download --skip-existing --pattern '*' \
            --repo "$TARGET_REPOSITORY" "$STAGING_TAG"

    - name: Create repo
      uses: callmetango/archlinux-make-repo-action@HEAD
      with:
        reponame: ${{ env.REPO_NAME }}

    - name: Release new release
      shell: sh
      env:
        APP_TOKEN: ${{ steps.app-token.outputs.token }}
      run: |
        "$SCRIPTS_DIR"/draft-new-release.sh "$TARGET_REPOSITORY" \
            "$NEXT_RELEASE_TAG" 'true'
        gh release upload --repo "$TARGET_REPOSITORY" "$NEXT_RELEASE_TAG" \
            *.pkg.* "$REPO_NAME".files* "$REPO_NAME".db*
        "$SCRIPTS_DIR"/release-new-release.sh "$TARGET_REPOSITORY" \
            "$CURRENT_RELEASE_TAG" "$NEXT_RELEASE_TAG"
        gh release delete --yes --repo "$TARGET_REPOSITORY" "$STAGING_TAG"
