# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2026 callmetango for XLibre

name: Build All and Publish

on:
  workflow_dispatch:
    inputs:
      force-build:
        description: Force the build of all packages
        type: boolean
        default: false
      branch:
        description: The branch to build
        type: choice
        options:
          - beta
          - master
          - oldstable
        default: master

env:
  CARCH: x86_64

jobs:
  _setup:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/draft-release
        with:
          branch: ${{ inputs.branch }}
          force-build: ${{ inputs.force-build }}
          app-client-id: ${{ vars.APP_CLIENT_ID }}
          app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
  xlibre-input-elographics:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - xlibre-xserver
    with:
      package: xlibre-input-elographics
      branch: ${{ inputs.branch }}
      force-build: ${{ inputs.force-build }}
    secrets: inherit

  xlibre-input-evdev:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - xlibre-xserver
    with:
      package: xlibre-input-evdev
      branch: ${{ inputs.branch }}
      force-build: ${{ inputs.force-build }}
    secrets: inherit

  xlibre-input-libinput:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - xlibre-xserver
    with:
      package: xlibre-input-libinput
      branch: ${{ inputs.branch }}
      force-build: ${{ inputs.force-build }}
    secrets: inherit

  xlibre-input-synaptics:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - xlibre-xserver
    with:
      package: xlibre-input-synaptics
      branch: ${{ inputs.branch }}
      force-build: ${{ inputs.force-build }}
    secrets: inherit

  xlibre-input-vmmouse:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - xlibre-xserver
    with:
      package: xlibre-input-vmmouse
      branch: ${{ inputs.branch }}
      force-build: ${{ inputs.force-build }}
    secrets: inherit

  xlibre-input-void:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - xlibre-xserver
    with:
      package: xlibre-input-void
      branch: ${{ inputs.branch }}
      force-build: ${{ inputs.force-build }}
    secrets: inherit

  xlibre-input-wacom:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - xlibre-xserver
    with:
      package: xlibre-input-wacom
      branch: ${{ inputs.branch }}
      force-build: ${{ inputs.force-build }}
    secrets: inherit

  xlibre-meta:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - xlibre-input-libinput
      - xlibre-xserver
    with:
      package: xlibre-meta
      branch: ${{ inputs.branch }}
      force-build: ${{ inputs.force-build }}
    secrets: inherit

  xlibre-video-amdgpu:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - xlibre-xserver
    with:
      package: xlibre-video-amdgpu
      branch: ${{ inputs.branch }}
      force-build: ${{ inputs.force-build }}
    secrets: inherit

  xlibre-video-ati:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - xlibre-xserver
    with:
      package: xlibre-video-ati
      branch: ${{ inputs.branch }}
      force-build: ${{ inputs.force-build }}
    secrets: inherit

  xlibre-video-dummy:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - xlibre-xserver
    with:
      package: xlibre-video-dummy
      branch: ${{ inputs.branch }}
      force-build: ${{ inputs.force-build }}
    secrets: inherit

  xlibre-video-fbdev:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - xlibre-xserver
    with:
      package: xlibre-video-fbdev
      branch: ${{ inputs.branch }}
      force-build: ${{ inputs.force-build }}
    secrets: inherit

  xlibre-video-intel:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - xlibre-xserver
    with:
      package: xlibre-video-intel
      branch: ${{ inputs.branch }}
      force-build: ${{ inputs.force-build }}
    secrets: inherit

  xlibre-video-nouveau:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - xlibre-xserver
    with:
      package: xlibre-video-nouveau
      branch: ${{ inputs.branch }}
      force-build: ${{ inputs.force-build }}
    secrets: inherit

  xlibre-video-qxl:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - xlibre-xserver
    with:
      package: xlibre-video-qxl
      branch: ${{ inputs.branch }}
      force-build: ${{ inputs.force-build }}
    secrets: inherit

  xlibre-video-sisusb:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - xlibre-xserver
    with:
      package: xlibre-video-sisusb
      branch: ${{ inputs.branch }}
      force-build: ${{ inputs.force-build }}
    secrets: inherit

  xlibre-video-vesa:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - xlibre-xserver
    with:
      package: xlibre-video-vesa
      branch: ${{ inputs.branch }}
      force-build: ${{ inputs.force-build }}
    secrets: inherit

  xlibre-video-vmware:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - xlibre-xserver
    with:
      package: xlibre-video-vmware
      branch: ${{ inputs.branch }}
      force-build: ${{ inputs.force-build }}
    secrets: inherit

  xlibre-video-voodoo:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
      - xlibre-xserver
    with:
      package: xlibre-video-voodoo
      branch: ${{ inputs.branch }}
      force-build: ${{ inputs.force-build }}
    secrets: inherit

  xlibre-xserver:
    uses: ./.github/workflows/build-package.yml
    needs:
      - _setup
    with:
      package: xlibre-xserver
      branch: ${{ inputs.branch }}
      force-build: ${{ inputs.force-build }}
    secrets: inherit

  all-packages:
    runs-on: ubuntu-24.04
    needs:
      - xlibre-input-elographics
      - xlibre-input-evdev
      - xlibre-input-libinput
      - xlibre-input-synaptics
      - xlibre-input-vmmouse
      - xlibre-input-void
      - xlibre-input-wacom
      - xlibre-meta
      - xlibre-video-amdgpu
      - xlibre-video-ati
      - xlibre-video-dummy
      - xlibre-video-fbdev
      - xlibre-video-intel
      - xlibre-video-nouveau
      - xlibre-video-qxl
      - xlibre-video-sisusb
      - xlibre-video-vesa
      - xlibre-video-vmware
      - xlibre-video-voodoo
      - xlibre-xserver
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/release-packages
        with:
          repository: ${{ vars.PACKAGES_REPOSITORY }}
          branch: ${{ inputs.branch }}
          repo-db-prefix: ${{ vars.REPO_DB_PREFIX }}
          app-client-id: ${{ vars.APP_CLIENT_ID }}
          app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
