# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2026 callmetango for XLibre

name: Build Package

on:
  workflow_call:
    inputs:
      repository:
        description: |-
          Location of the GitHub repository containing the package descriptions
          in the form of [HOST/]OWNER/REPO.
        type: string
        default: ${{ vars.PACKAGES_REPOSITORY }}
      branch:
        description: The branch to build
        type: string
        required: true
      package:
        description: |-
          The name of the package to build. Must be a subdirectory of the repository.
        type: string
        required: true
      packager:
        type: string
        description: >
          The builder of the packages in the form of a name and an email address in
          the form of John Doe <john@example.com>
        default: ${{ vars.PACKAGER }}
      docker-image:
        description: The name of the docker image to use
        type: string
        default: ${{ vars.DOCKER_IMAGE }}
      force-build:
        description: |-
          Force the build of the package. Replaces an eventually existing release
          with the result of this build run.
        type: boolean

      # App-based authentication
      app-client-id:
        description: GitHub App Client ID
        type: string
        default: ${{ vars.APP_CLIENT_ID }}

      # PGP key handling
      pgp-key:
        description: PGP key file to use for verifying packages
        type: string
        default: ${{ vars.RELEASE_SIGNING_PUBLIC_KEY }}
    secrets:
      APP_PRIVATE_KEY:
        description: GitHub App private key
      RELEASE_SIGNING_KEY:
        description: The OpenPGP key to sign the packages
      RELEASE_SIGNING_KEY_PASSWORD:
        description: The password of the signing key

defaults:
  run:
    shell: sh

jobs:
  build-package:
    runs-on: ubuntu-24.04
    env:
      CARCH: x86_64 # TODO make configurable
      BUILD_NEEDED: ${{ inputs.force-build }}
      INPUT_BRANCH: ${{ inputs.branch }}
      INPUT_PACKAGE: ${{ inputs.package }}
      SCRIPTS_DIR: ${{ github.workspace }}/workflow/.github/scripts
    steps:
      - name: Authenticate via app
        id: app-token
        if: ${{ inputs.app-client-id }}
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ inputs.app-client-id }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout workflow # so we can run our own scripts
        uses: actions/checkout@v6
        with:
          path: workflow

      - name: Checkout package definitions
        uses: actions/checkout@v6
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.branch }}
          path: pkgbuilds

      - name: Set up environment
        env:
          APP_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          "${SCRIPTS_DIR}"/setup-build-env.sh

      - name: Copy assets or set BUILD_NEEDED
        if: ${{ env.BUILD_NEEDED != 'true' }}
        working-directory: pkgbuilds
        run: |
          "${SCRIPTS_DIR}"/try-copy-assets.sh "$TARGET_REPOSITORY" \
              "$CURRENT_RELEASE_TAG" "$STAGING_TAG" "$INPUT_PACKAGE"

      - name: Download dependencies
        if: ${{ env.BUILD_NEEDED == 'true' }}
        working-directory: pkgbuilds
        run: |
          "${SCRIPTS_DIR}"/download-dependencies.sh "$TARGET_REPOSITORY" \
              "$STAGING_TAG" "$INPUT_PACKAGE"

      - name: Build package
        if: ${{ env.BUILD_NEEDED == 'true' }}
        uses: callmetango/archlinux-build-package-action@next
        with:
          path: pkgbuilds/${{ inputs.package }}
          packager: ${{ inputs.packager }}
          docker-image: ${{ inputs.docker-image }}
          makepkg-opts: --syncdeps --noconfirm
          srcinfo: false
          pgp-key: ${{ inputs.pgp-key }}
          signing-key: ${{ secrets.RELEASE_SIGNING_KEY }}
          signing-key-password: ${{ secrets.RELEASE_SIGNING_KEY_PASSWORD }}
          dependencies-path: pkgbuilds/dependencies

      - name: Re-authenticate via app
        id: reauth
        if: ${{ env.BUILD_NEEDED == 'true' && inputs.app-client-id }}
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ inputs.app-client-id }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Release package
        if: ${{ env.BUILD_NEEDED == 'true' }}
        env:
          GH_TOKEN: ${{ steps.reauth.outputs.token }}
        working-directory: pkgbuilds
        run: |
          gh release upload --repo "$TARGET_REPOSITORY" \
              "$STAGING_TAG" "$INPUT_PACKAGE"/*.pkg.*
